INSERT INTO "fields" ("name", "label", "parent_object", "object_name", "datatype", "relationship_name") VALUES
    ('owner_id', 'Owner', 'users', 'dashboard_folder', 'lookup_relationship', 'owner'),
    ('created_by_id', 'Created By', 'users', 'dashboard_folder', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'dashboard_folder', 'lookup_relationship', 'last_modified_by'),
    ('profile_id', 'Profile', 'profile', 'app_permissions', 'lookup_relationship', 'profile'),
    ('app_id', 'App', 'app', 'app_permissions', 'lookup_relationship', 'app'),
    ('user_id', 'User', 'users', 'audit_trail_track', 'lookup_relationship', 'user'),
    ('group_id', 'Group', 'auth_group', 'auth_group_permissions', 'lookup_relationship', 'group'),
    ('permission_id', 'Permission', 'auth_permission', 'auth_group_permissions', 'lookup_relationship', 'permission'),
    ('content_type_id', 'Content Type', 'django_content_type', 'auth_permission', 'lookup_relationship', 'content_type'),
    ('telephony_id', 'Telephony', 'telephony_config', 'call_logs', 'lookup_relationship', 'telephony'),
    ('region_id', 'Region', 'regions', 'customers', 'lookup_relationship', 'region'),
    ('content_type_id', 'Content Type', 'django_content_type', 'django_admin_log', 'lookup_relationship', 'content_type'),
    ('user_id', 'User', 'users', 'django_admin_log', 'lookup_relationship', 'user'),
    ('crontab_id', 'Crontab', 'django_celery_beat_crontabschedule', 'django_celery_beat_periodictask', 'lookup_relationship', 'crontab'),
    ('interval_id', 'Interval', 'django_celery_beat_intervalschedule', 'django_celery_beat_periodictask', 'lookup_relationship', 'interval'),
    ('solar_id', 'Solar', 'django_celery_beat_solarschedule', 'django_celery_beat_periodictask', 'lookup_relationship', 'solar'),
    ('clocked_id', 'Clocked', 'django_celery_beat_clockedschedule', 'django_celery_beat_periodictask', 'lookup_relationship', 'clocked'),
    ('author_id', 'Author', 'users', 'email_templates', 'lookup_relationship', 'author'),
    ('selected_object', 'Selected Object', 'object', 'email_templates', 'lookup_relationship', 'selected_object'),
    ('fields_id', 'Fields', 'fields', 'field_permissions', 'lookup_relationship', 'fields'),
    ('object_id', 'Object', 'object', 'field_permissions', 'lookup_relationship', 'object'),
    ('profile_id', 'Profile', 'profile', 'field_permissions', 'lookup_relationship', 'profile'),
    ('object_id', 'Object', 'object', 'fields', 'lookup_relationship', 'object'),
    ('created_by_id', 'Created By', 'users', 'file', 'lookup_relationship', 'created_by'),
    ('deleted_by_id', 'Deleted By', 'users', 'file', 'lookup_relationship', 'deleted_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'file', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'file', 'lookup_relationship', 'owner'),
    ('created_by_id', 'Created By', 'users', 'hsitory', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'hsitory', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'hsitory', 'lookup_relationship', 'owner'),
    ('invoice_id', 'Invoice', 'invoices', 'invoice_items', 'lookup_relationship', 'invoice'),
    ('product_id', 'Product', 'products', 'invoice_items', 'lookup_relationship', 'product'),
    ('customer_id', 'Customer', 'customers', 'invoices', 'lookup_relationship', 'customer'),
    ('telephony_id', 'Telephony', 'telephony_config', 'landing_numbers', 'lookup_relationship', 'telephony'),
    ('group_id', 'Group', 'user_group', 'landing_numbers', 'lookup_relationship', 'group'),
    ('profile_id', 'Profile', 'profile', 'layout_assignment', 'lookup_relationship', 'profile'),
    ('object_id', 'Object', 'object', 'layout_assignment', 'lookup_relationship', 'object'),
    ('page_layouts_id', 'Page Layouts', 'page_layouts', 'layout_assignment', 'lookup_relationship', 'page_layouts'),
    ('created_by_id', 'Created By', 'users', 'layout_assignment', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'layout_assignment', 'lookup_relationship', 'last_modified_by'),
    ('created_by_id', 'Created By', 'users', 'lead_capture', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'lead_capture', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'lead_capture', 'lookup_relationship', 'owner'),
    ('object_id', 'Object', 'object', 'listviews', 'lookup_relationship', 'object'),
    ('channel_id', 'Channel', 'channel', 'message', 'lookup_relationship', 'channel'),
    ('workflow_id', 'Workflow', 'workflow', 'node', 'lookup_relationship', 'workflow'),
    ('created_by_id', 'Created By', 'users', 'node', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'node', 'lookup_relationship', 'last_modified_by'),
    ('object_id', 'Object', 'object', 'object_permissions', 'lookup_relationship', 'object'),
    ('profile_id', 'Profile', 'profile', 'object_permissions', 'lookup_relationship', 'profile'),
    ('object_id', 'Object', 'object', 'path_builder', 'lookup_relationship', 'object'),
    ('field_id', 'Field', 'fields', 'path_builder', 'lookup_relationship', 'field'),
    ('created_by_id', 'Created By', 'users', 'path_builder', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'path_builder', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'path_builder', 'lookup_relationship', 'owner'),
    ('created_by_id', 'Created By', 'users', 'sales', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'sales', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'sales', 'lookup_relationship', 'owner'),
    ('object_id', 'Object', 'object', 'search_layouts', 'lookup_relationship', 'object'),
    ('user_id', 'User', 'users', 'session_log', 'lookup_relationship', 'user'),
    ('created_by_id', 'Created By', 'users', 'setup', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'setup', 'lookup_relationship', 'last_modified_by'),
    ('owner_id', 'Owner', 'users', 'setup', 'lookup_relationship', 'owner'),
    ('object_id', 'Object', 'object', 'sharing_records', 'lookup_relationship', 'object'),
    ('profile_id', 'Profile', 'profile', 'tab_permissions', 'lookup_relationship', 'profile'),
    ('object_id', 'Object', 'object', 'tab_permissions', 'lookup_relationship', 'object'),
    ('assigned_to_id', 'Assigned To', 'users', 'task', 'lookup_relationship', 'assigned_to'),
    ('created_by_id', 'Created By', 'users', 'task', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'task', 'lookup_relationship', 'last_modified_by'),
    ('related_to_content_type_id', 'Related To Content Type', 'django_content_type', 'task', 'lookup_relationship', 'related_to_content_type'),
    ('created_by_id', 'Created By', 'users', 'theme', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'theme', 'lookup_relationship', 'last_modified_by'),
    ('created_by', 'Created By', 'users', 'user_group', 'lookup_relationship', 'created_by'),
    ('modified_by', 'Modified By', 'users', 'user_group', 'lookup_relationship', 'modified_by'),
    ('user_group_id', 'User Group', 'user_group', 'user_group_users', 'lookup_relationship', 'user_group'),
    ('user_id', 'User', 'users', 'user_group_users', 'lookup_relationship', 'user'),
    ('users_id', 'Users', 'users', 'user_login_history', 'lookup_relationship', 'users'),
    ('user_id', 'User', 'users', 'users_user_permissions', 'lookup_relationship', 'user'),
    ('permission_id', 'Permission', 'auth_permission', 'users_user_permissions', 'lookup_relationship', 'permission'),
    ('created_by_id', 'Created By', 'users', 'workflow', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'workflow', 'lookup_relationship', 'last_modified_by'),
    ('workflow_id', 'Workflow', 'workflow', 'workflow_edge', 'lookup_relationship', 'workflow'),
    ('source', 'Source', 'workflow_node', 'workflow_edge', 'lookup_relationship', 'source'),
    ('target', 'Target', 'workflow_node', 'workflow_edge', 'lookup_relationship', 'target'),
    ('created_by_id', 'Created By', 'users', 'workflow_edge', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'workflow_edge', 'lookup_relationship', 'last_modified_by'),
    ('workflow_id', 'Workflow', 'workflow', 'workflow_node', 'lookup_relationship', 'workflow'),
    ('created_by_id', 'Created By', 'users', 'workflow_node', 'lookup_relationship', 'created_by'),
    ('last_modified_by_id', 'Last Modified By', 'users', 'workflow_node', 'lookup_relationship', 'last_modified_by'),
    ('profile_id', 'Profile', 'profile', 'page_builder_assignment', 'lookup_relationship', 'profile'),
    ('page_builder_id', 'Page Builder', 'page_builder', 'page_builder_assignment', 'lookup_relationship', 'page_builder'),
    ('profile_id', 'Profile', 'profile', 'homepage_assignment', 'lookup_relationship', 'profile'),
    ('page_id', 'Page', 'page_builder', 'homepage_assignment', 'lookup_relationship', 'page'),
    ('profile_id', 'Profile', 'profile', 'users', 'lookup_relationship', 'profile'),
    ('organization_id', 'Organization', 'organizations', 'users', 'lookup_relationship', 'organization'),
    ('manager_id', 'Manager', 'users', 'users', 'lookup_relationship', 'manager');
