# Generated by Django 5.1.5 on 2025-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, unique=True)),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salesforce Metadata',
                'verbose_name_plural': 'Salesforce Metadata',
                'db_table': 'salesforce_metadata',
            },
        ),
        migrations.CreateModel(
            name='SalesforceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salesforce Setting',
                'verbose_name_plural': 'Salesforce Settings',
                'db_table': 'salesforce_settings',
            },
        ),
        migrations.CreateModel(
            name='SalesforceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('syncing_frequency', models.IntegerField(default=30)),
                ('salesforce_pull', models.BooleanField(default=False)),
                ('salesforce_push', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Salesforce Sync',
                'verbose_name_plural': 'Salesforce Sync',
                'db_table': 'salesforce_sync',
            },
        ),
    ]
