"""
Django settings for version2 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import environ
import os
from dotenv import load_dotenv
load_dotenv()
from corsheaders.defaults import default_headers

# -------------------------------
# Sentry — install + initialize unconditionally; sentry-sdk no-ops cleanly
# when SENTRY_DSN is unset, so dev/test stay quiet but production gets full
# error visibility.
# -------------------------------
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    import logging as _stdlib_logging

    _SENTRY_DSN = os.getenv("SENTRY_DSN", "")
    if _SENTRY_DSN:
        sentry_sdk.init(
            dsn=_SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                CeleryIntegration(),
                # Forward WARNING+ stdlib logs as breadcrumbs and ERROR+ as events
                LoggingIntegration(
                    level=_stdlib_logging.INFO,
                    event_level=_stdlib_logging.ERROR,
                ),
            ],
            release=os.getenv("GIT_SHA", os.getenv("RELEASE", "dev")),
            environment=os.getenv("DJANGO_ENV", "development"),
            send_default_pii=False,
            traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
            profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0")),
        )
except Exception:
    # Never let observability tooling block app startup.
    pass

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)  # Default DEBUG=False
)

# Determine if we're in development or production
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")  # Default: development

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if ENVIRONMENT == "production":
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
else:
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Salesforce Credentials
SALESFORCE_USERNAME = os.getenv("SALESFORCE_USERNAME")
SALESFORCE_PASSWORD = os.getenv("SALESFORCE_PASSWORD")
SALESFORCE_CLIENT_ID = os.getenv("SALESFORCE_CLIENT_ID")
SALESFORCE_CLIENT_SECRET = os.getenv("SALESFORCE_CLIENT_SECRET")

FACEBOOK_APP_ID = os.getenv('FACEBOOK_APP_ID')
FACEBOOK_APP_SECRET = os.getenv('FACEBOOK_APP_SECRET')
FACEBOOK_GRAPH_API_VERSION = os.getenv('FACEBOOK_GRAPH_API_VERSION', 'v13.0')
FACEBOOK_REDIRECT_URI = os.getenv('FACEBOOK_REDIRECT_URI', 'http://localhost:8000/facebook/login/redirect/')

WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN')
WHATSAPP_PHONE_NUMBER = os.getenv('WHATSAPP_PHONE_NUMBER')
WHATSAPP_BA_APP_ID = os.getenv('WHATSAPP_BA_APP_ID')

MEDIA_ROOT = os.getenv('MEDIA_ROOT', '/var/www/media/')
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')

# Use Redis as a broker
CELERY_BROKER_URL = os.getenv('REDIS_URL')

# Result backend (optional, stores task results)
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL')

# Task serialization format
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ✅ Fix for Celery 6.x deprecation warning
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtpout.secureserver.net")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default — must be set via environment. App fails fast on boot if missing,
# preventing accidental shipping with the well-known insecure dev key.
try:
    SECRET_KEY = env("SECRET_KEY")
except Exception as _e:
    raise ValueError(
        "SECRET_KEY must be set in the environment. Generate one with "
        "`python -c \"from django.core.management.utils import get_random_secret_key; "
        "print(get_random_secret_key())\"` and add it to your secrets store."
    ) from _e
if len(SECRET_KEY) < 50:
    raise ValueError(
        "SECRET_KEY is too short (need >=50 chars). Regenerate with "
        "django.core.management.utils.get_random_secret_key()."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# -------------------------------
# Django Cache Configuration
# -------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "TIMEOUT": None,  # disable global expiry (set TTL per item)
    }
}



# ALLOWED_HOSTS should be configured per environment
# Development default includes localhost, production should set via environment
if ENVIRONMENT == "production":
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")  # Must be explicitly set in production
else:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['localhost', '127.0.0.1','*','10.221.187.152'])
    print("ALLOWED_HOSTS:", ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = [
    'https://qa.bussus.com/',
    'https://dev.bussus.com/',
    'https://production.bussus.com/',
    'http://127.0.0.1:8000/',
    'http://localhost:3000/',
    'https://bussus-backend.azurewebsites.net',
    'https://bussus-frontend.azurewebsites.net',
    'https://*.bussus.com',
]

AUTH_USER_MODEL = 'api.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'facebook',
    'sf_integration',
    'django_celery_beat',
    'whatsapp',
    "data_export",
    'channels',
    'api.emailsend',
    'public',
    'adminuser',
    'django_extensions'
]

MIDDLEWARE = [
    # Correlation ID FIRST so every other middleware's logs carry the trace_id.
    'api.security.correlation.RequestCorrelationMiddleware',
    # Sentry tag enrichment runs SECOND — Sentry events raised by any
    # later middleware or view body inherit tenant_id + user_id tags
    # automatically. No-op if sentry-sdk isn't installed.
    'api.security.sentry_tags.SentryTenantTagMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # "middleware.middleware.JWTAuthenticationMiddleware",  # JWT middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Tenant-schema middleware runs `process_view`, so it executes AFTER
    # the dispatcher's _init_request_context has called pin_request_tenant
    # and request.tenant_schema is populated. It then `SET search_path`
    # so subsequent Django ORM queries (Profile.objects.get(...) etc.)
    # automatically scope to the right tenant.
    'api.security.tenant_schema_middleware.TenantSchemaMiddleware',
    # Statement-timeout LAST in the chain so it sees the resolved URL
    # (CommonMiddleware's append-slash redirect runs first) and the
    # timeout only applies to the actual view handling.
    'api.security.statement_timeout.StatementTimeoutMiddleware',
    # 'api.middleware.SharingMiddleware',
]


# -------------------------------
# Structured logging
# -------------------------------
# JSON formatter when LOG_FORMAT=json (production); text otherwise (dev).
# RequestContextFilter injects trace_id/tenant_id/user_id from contextvars
# into every record, so log lines carry request-correlation IDs even when
# emitted from nested layers (BL, ORM, Celery).
_LOG_FORMAT = os.getenv("LOG_FORMAT", "text").lower()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "api.security.correlation.RequestContextFilter",
        },
    },
    "formatters": {
        "text": {
            "format": (
                "%(asctime)s %(levelname)s %(name)s "
                "[trace=%(trace_id)s tenant=%(tenant_id)s user=%(user_id)s] "
                "%(message)s"
            ),
        },
        "json": {
            "()": "logging.Formatter",
            "format": (
                '{"ts":"%(asctime)s","level":"%(levelname)s",'
                '"logger":"%(name)s","trace_id":"%(trace_id)s",'
                '"tenant_id":"%(tenant_id)s","user_id":"%(user_id)s",'
                '"msg":%(message)r}'
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if _LOG_FORMAT == "json" else "text",
            "filters": ["request_context"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        # Django's request logger is too chatty at INFO and reasonable at WARNING.
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


ROOT_URLCONF = 'version2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'version2.wsgi.application'
ASGI_APPLICATION = 'version2.asgi.application'  # Replace with your actual project name

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DATABASE_NAME"),    # Database name
        'USER': env('DATABASE_USER'),    # Database user
        'PASSWORD': env('DATABASE_PASSWORD'),  # User's password
        'HOST': env("DATABASE_HOST"),                 #'88.222.241.78',             # Hostname (or IP address)
        'PORT': env("DATABASE_PORT"),                  # Port (default for PostgreSQL)

        # Phase 4 part 1: wrap every view in a transaction. Two reasons:
        #   1. The TenantSchemaMiddleware issues `SET LOCAL search_path`
        #      and `SET LOCAL ROLE` per request. Those statements only
        #      hold for the duration of a transaction; without
        #      ATOMIC_REQUESTS the SET LOCAL is essentially a no-op
        #      because Django runs each statement in its own implicit
        #      transaction.
        #   2. If a view raises mid-write, the transaction rolls back
        #      cleanly — no half-committed records.
        # The cost is one BEGIN/COMMIT pair per request, which is
        # negligible against the multi-statement cost of any real view.
        'ATOMIC_REQUESTS': True,

        # Phase 4 part 1: don't reuse connections across requests.
        # The `SET LOCAL` statements reset on transaction end (above),
        # but a stale `SET` (without LOCAL) on a previous request
        # could still leak into the next one. CONN_MAX_AGE=0 forces
        # a fresh connection per request, which is the cleanest
        # safety net during the rollout. Once pgBouncer is in
        # place (the 10-risk #7 item), we can revisit.
        'CONN_MAX_AGE': 0,
    }
}

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")

# Phase 2.A4 — DRF auth gate, behind a feature flag.
#
# Plain English
# -------------
# Today, DRF doesn't apply authentication or "must be authenticated"
# permission by default to any view. The dispatcher explicitly sets
# `permission_classes = [IsAuthenticated]`, so the heavily-trafficked
# API path is safe. But any other view (across adminuser/, public/,
# facebook/, whatsapp/, sf_integration/, data_export/) is authenticated
# ONLY if the view explicitly declares it.
#
# Once `STRICT_AUTH=1` is set in the environment, DRF defaults to
# "require JWT + IsAuthenticated" globally. Every view that's
# legitimately public (login, OTP, OAuth callbacks, signup, webhooks,
# health probes) MUST then explicitly declare
#   permission_classes = [AllowAny]; authentication_classes = []
# otherwise it 401s.
#
# The flag is OFF by default during rollout. The operator flips it to 1
# after:
#   * Reviewing docs/security/url_audit.md (URL inventory + REVIEW items)
#   * Running 48h of staging traffic with STRICT_AUTH=1 and triaging
#     every unexpected 401
#   * Confirming every webhook endpoint HMAC-verifies before any BL
#
# See docs/SEC_PHASE2_A4_OPERATOR_NOTES.md for the full procedure.
STRICT_AUTH = env.bool("STRICT_AUTH", default=False)

if STRICT_AUTH:
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'authentication.custom_jwt_auth.CustomJWTAuthentication',
        ),
        'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated',
        ),
    }
else:
    # Pre-A4 behaviour: no global defaults. Individual views set their
    # own. The Dispatcher already sets [IsAuthenticated]; the rest of
    # the codebase relies on view-level declarations.
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (),
        'DEFAULT_PERMISSION_CLASSES': (),
    }


# settings.py

CHANNEL_LAYERS = {
    "default": {
        #"BACKEND": "channels.layers.InMemoryChannelLayer",  # For development/testing only
        # For production with Redis, use:
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [ os.getenv(
                    "REDIS_URL",
                    "redis://:Fingertip%402025@127.0.0.1:6379/0"
                )
            ],
        },
    },
}

# Validate critical security settings
try:
    JWT_SECRET_KEY = env("JWT_SECRET_KEY")  # No default - must be set in environment
    if not JWT_SECRET_KEY or len(JWT_SECRET_KEY) < 32:
        raise ValueError("JWT_SECRET_KEY must be set and be at least 32 characters long")
except Exception as e:
    raise ValueError(f"Critical security configuration error: {e}. Please set JWT_SECRET_KEY in environment variables.")

# SCHEMA_AUTHORITY_ENFORCE controls whether ``assert_pinned_schema`` raises
# on cross-tenant kwarg mismatches (value "1") or merely logs them
# (value "0"). The "0" setting exists only as a transitional escape hatch
# during the schema-authority rollout and MUST NOT be used in production
# — log-only mode permits cross-tenant access to slip through.
#
# Refusing to start with the wrong value (instead of just relying on it
# being set correctly in deployment) prevents an operator accident from
# silently disabling the enforcement.
_schema_authority_enforce = os.getenv("SCHEMA_AUTHORITY_ENFORCE", "1")
if ENVIRONMENT == "production" and _schema_authority_enforce != "1":
    raise ValueError(
        "SCHEMA_AUTHORITY_ENFORCE must be '1' in production "
        "(found %r). Log-only mode (value '0') is a development/soak "
        "escape hatch only — running production without enforcement "
        "leaves cross-tenant access guarded by app-layer logs alone."
        % _schema_authority_enforce
    )

SIMPLE_JWT = {
    # Phase C5 — access-token lifetime cut from 12h to 30 min.
    # A 12-hour access token is a 12-hour window for a stolen token
    # (via a logged URL, a shared device, an XSS payload) to be
    # replayed. 30 minutes bounds that window; the 7-day refresh
    # token + ROTATE_REFRESH_TOKENS keeps the user logged in without
    # re-entering their password. Overridable via env for tuning.
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=env.int("JWT_ACCESS_MINUTES", default=30)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=env.int("JWT_REFRESH_DAYS", default=7)
    ),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": JWT_SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'BLACKLIST_AFTER_ROTATION': True,
    'ROTATE_REFRESH_TOKENS': True,
}

AUTHENTICATION_BACKENDS = [
    'api.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default session storage
# SESSION_COOKIE_SECURE: defaults secure-by-default in production. Overridable
# via env for local HTTPS testing. See ``Security Settings`` block below for
# the rest of the cookie/HSTS hardening defaults.
SESSION_COOKIE_SECURE = env.bool(
    "SESSION_COOKIE_SECURE",
    default=(ENVIRONMENT == "production"),
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Phase C6 — bumped the minimum from Django's default 8 to 10.
        # 8 characters is brute-forceable; 10 is a meaningful step up
        # without being annoying for users.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Phase C6 — reject passwords found in the Have I Been Pwned
        # breach corpus (hundreds of millions of real leaked passwords).
        # Uses the k-anonymity range API: HIBP only ever sees the first
        # 5 chars of the SHA-1, never the password. Fails OPEN on a
        # network error so a HIBP outage can't block all signups.
        'NAME': 'api.security.password_validators.BreachedPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)

CORS_ALLOWED_ORIGINS = [
    "https://fullstack-frontend.azurewebsites.net",
    "https://dev.bussus.com",
    "https://qa.bussus.com",
    "https://bussus.com",
    "https://*.bussus.com",
    # "http://localhost:3000/",
    # "http://localhost:3001/",

]

CORS_ALLOW_HEADERS = list(default_headers) +["X-Frontend-URL","SCHEMA"]

# -------------------------------
# Rate limiting (django-ratelimit) — Phase 8.A7
# -------------------------------
# The auth views (login, OTP, password reset, signup) already use the
# @ratelimit decorator, but historically without block=True they only
# set request.limited and never enforced. The Phase 8.A7 branch flipped
# every decorator to block=True so the library issues the 429 itself.
#
# RATELIMIT_ENABLE defaults to True in django-ratelimit; we set it
# explicitly so an operator can disable rate limiting (e.g. for load
# testing) without code edits — RATELIMIT_ENABLE=0 in the env.
#
# RATELIMIT_USE_CACHE points at the Redis backend already defined in
# CACHES['default'] above. This means rate-limit counters survive a
# single worker process restart (in-memory counters wouldn't).
RATELIMIT_ENABLE = env.bool("RATELIMIT_ENABLE", default=True)
RATELIMIT_USE_CACHE = "default"
# Progressive-lockout thresholds (consumed by public.auth.lockout).
# After N failed logins in WINDOW_MINUTES, the account is rejected for
# LOCKOUT_MINUTES. Numbers chosen to be aggressive against brute-force
# while not punishing a user who fumbles their password a few times.
AUTH_LOCKOUT_THRESHOLD = env.int("AUTH_LOCKOUT_THRESHOLD", default=5)
AUTH_LOCKOUT_WINDOW_MINUTES = env.int("AUTH_LOCKOUT_WINDOW_MINUTES", default=15)
AUTH_LOCKOUT_MINUTES = env.int("AUTH_LOCKOUT_MINUTES", default=15)

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Production-safe defaults for HSTS, SSL redirect, and Secure cookies.
# Each value can still be overridden via env (useful for local HTTPS testing
# or for staging environments that do their own TLS termination); but the
# DEFAULT is "on" once ENVIRONMENT=production, so a misconfigured prod
# environment doesn't silently ship without HSTS or with insecure cookies.
_IS_PROD = (ENVIRONMENT == "production")
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS",
    default=31536000 if _IS_PROD else 0,   # 1 year in prod, off elsewhere
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=_IS_PROD,
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=_IS_PROD)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=_IS_PROD)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=_IS_PROD)

# Tell Django to trust the X-Forwarded-Proto header when running behind
# a TLS-terminating reverse proxy (the standard prod topology). Off in
# non-prod to avoid spoofing risk in environments without a real proxy.
if _IS_PROD:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# OTP security knobs
OTP_LENGTH = int(os.getenv("OTP_LENGTH", "6"))
OTP_TTL_SECONDS = int(os.getenv("OTP_TTL_SECONDS", "600"))
OTP_RESEND_COOLDOWN = int(os.getenv("OTP_RESEND_COOLDOWN", "60"))
OTP_MAX_ATTEMPTS = int(os.getenv("OTP_MAX_ATTEMPTS", "5"))
OTP_MAX_SENDS = int(os.getenv("OTP_MAX_SENDS", "5"))

# Password hashers (to hash OTPs)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


NYLAS_API_KEY = os.getenv("NYLAS_API_KEY")
NYLAS_API_URL = os.getenv("NYLAS_API_URL")
NYLAS_CLIENT_ID = os.getenv("NYLAS_CLIENT_ID")

# Logging Configuration
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': env('DJANGO_LOG_LEVEL', default='INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}
# Phase C5 — request-body size limits (DoS hardening).
#
# DATA_UPLOAD_MAX_MEMORY_SIZE caps the NON-FILE portion of a request
# body. Django streams multipart FILE parts straight to disk and they
# do NOT count toward this limit — so the previous 500 MB value did
# NOT actually enable large file uploads, it just allowed a 500 MB
# JSON body into memory. A handful of concurrent 500 MB JSON POSTs
# would exhaust server RAM (a trivial denial-of-service).
#
# 25 MB is still a very large JSON payload (well beyond any normal
# bulk operation). Operators who genuinely need more for a specific
# bulk-import endpoint can raise DATA_UPLOAD_MAX_MEMORY_MB in the env.
# File uploads are unaffected — they stream to disk via
# FILE_UPLOAD_MAX_MEMORY_SIZE and the import view's own size cap.
DATA_UPLOAD_MAX_MEMORY_SIZE = (
    env.int("DATA_UPLOAD_MAX_MEMORY_MB", default=25) * 1024 * 1024
)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024    # 5 MB before spilling to temp file
# Caps the number of form fields per request — protects against the
# hash-collision DoS (a request with hundreds of thousands of keys).
# 10k is far more than any legitimate form; was 100k.
DATA_UPLOAD_MAX_NUMBER_FIELDS = env.int(
    "DATA_UPLOAD_MAX_NUMBER_FIELDS", default=10000
)
