# Generated by Django 5.1.5 on 2026-03-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_user_last_modified_date_user_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
    ]
