INSERT INTO object (name, setup, label, plural_label) VALUES ('apex_class', TRUE, 'Apex Class', 'Apex Classes');
INSERT INTO object (name, setup, label, plural_label) VALUES ('app', TRUE, 'App', 'Apps');
INSERT INTO object (name, setup, label, plural_label) VALUES ('app_permissions', TRUE, 'App Permissions', 'App Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('approval_processes', TRUE, 'Approval Processes', 'Approval Processeses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('audit_trail_track', TRUE, 'Audit Trail Track', 'Audit Trail Tracks');
INSERT INTO object (name, setup, label, plural_label) VALUES ('audit_trails', TRUE, 'Audit Trails', 'Audit Trailses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('auth_group', TRUE, 'Auth Group', 'Auth Groups');
INSERT INTO object (name, setup, label, plural_label) VALUES ('auth_group_permissions', TRUE, 'Auth Group Permissions', 'Auth Group Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('auth_permission', TRUE, 'Auth Permission', 'Auth Permissions');
INSERT INTO object (name, setup, label, plural_label) VALUES ('call_logs', TRUE, 'Call Logs', 'Call Logses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('channel', TRUE, 'Channel', 'Channels');
INSERT INTO object (name, setup, label, plural_label) VALUES ('columns_metadata', TRUE, 'Columns Metadata', 'Columns Metadatas');
INSERT INTO object (name, setup, label, plural_label) VALUES ('component', TRUE, 'Component', 'Components');
INSERT INTO object (name, setup, label, plural_label) VALUES ('connected_app', TRUE, 'Connected App', 'Connected Apps');
INSERT INTO object (name, setup, label, plural_label) VALUES ('custom_metadata', TRUE, 'Custom Metadata', 'Custom Metadatas');
INSERT INTO object (name, setup, label, plural_label) VALUES ('custom_setting', TRUE, 'Custom Setting', 'Custom Settings');
INSERT INTO object (name, setup, label, plural_label) VALUES ('customers', TRUE, 'Customers', 'Customerses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('dashboard', TRUE, 'Dashboard', 'Dashboards');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_admin_log', TRUE, 'Django Admin Log', 'Django Admin Logs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_clockedschedule', TRUE, 'Django Celery Beat Clockedschedule', 'Django Celery Beat Clockedschedules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_crontabschedule', TRUE, 'Django Celery Beat Crontabschedule', 'Django Celery Beat Crontabschedules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_intervalschedule', TRUE, 'Django Celery Beat Intervalschedule', 'Django Celery Beat Intervalschedules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_periodictask', TRUE, 'Django Celery Beat Periodictask', 'Django Celery Beat Periodictasks');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_periodictasks', TRUE, 'Django Celery Beat Periodictasks', 'Django Celery Beat Periodictaskses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_celery_beat_solarschedule', TRUE, 'Django Celery Beat Solarschedule', 'Django Celery Beat Solarschedules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_content_type', TRUE, 'Django Content Type', 'Django Content Types');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_migrations', TRUE, 'Django Migrations', 'Django Migrationses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('django_session', TRUE, 'Django Session', 'Django Sessions');
INSERT INTO object (name, setup, label, plural_label) VALUES ('duplicate_rule', TRUE, 'Duplicate Rule', 'Duplicate Rules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('email_templates', TRUE, 'Email Templates', 'Email Templateses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('facebook_lead', TRUE, 'Facebook Lead', 'Facebook Leads');
INSERT INTO object (name, setup, label, plural_label) VALUES ('field_history_log', TRUE, 'Field History Log', 'Field History Logs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('field_permissions', TRUE, 'Field Permissions', 'Field Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('field_tracking_config', TRUE, 'Field Tracking Config', 'Field Tracking Configs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('fields', TRUE, 'Fields', 'Fieldses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('file', TRUE, 'File', 'Files');
INSERT INTO object (name, setup, label, plural_label) VALUES ('flows', TRUE, 'Flows', 'Flowses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('group_assignment_tracker', TRUE, 'Group Assignment Tracker', 'Group Assignment Trackers');
INSERT INTO object (name, setup, label, plural_label) VALUES ('hsitory', TRUE, 'Hsitory', 'Hsitories');
INSERT INTO object (name, setup, label, plural_label) VALUES ('import_wizard', TRUE, 'Import Wizard', 'Import Wizards');
INSERT INTO object (name, setup, label, plural_label) VALUES ('invoice_items', TRUE, 'Invoice Items', 'Invoice Itemses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('invoices', TRUE, 'Invoices', 'Invoiceses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('landing_numbers', TRUE, 'Landing Numbers', 'Landing Numberses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('layout_assignment', TRUE, 'Layout Assignment', 'Layout Assignments');
INSERT INTO object (name, setup, label, plural_label) VALUES ('lead_capture', TRUE, 'Lead Capture', 'Lead Captures');
INSERT INTO object (name, setup, label, plural_label) VALUES ('lightning_pages', TRUE, 'Lightning Pages', 'Lightning Pageses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('listviews', TRUE, 'Listviews', 'Listviewses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('matching_rule', TRUE, 'Matching Rule', 'Matching Rules');
INSERT INTO object (name, setup, label, plural_label) VALUES ('message', TRUE, 'Message', 'Messages');
INSERT INTO object (name, setup, label, plural_label) VALUES ('named_credential', TRUE, 'Named Credential', 'Named Credentials');
INSERT INTO object (name, setup, label, plural_label) VALUES ('node', TRUE, 'Node', 'Nodes');
INSERT INTO object (name, setup, label, plural_label) VALUES ('object', TRUE, 'Object', 'Objects');
INSERT INTO object (name, setup, label, plural_label) VALUES ('object_permissions', TRUE, 'Object Permissions', 'Object Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('opportunity_lineitem', TRUE, 'Opportunity Lineitem', 'Opportunity Lineitems');
INSERT INTO object (name, setup, label, plural_label) VALUES ('owd', TRUE, 'Owd', 'Owds');
INSERT INTO object (name, setup, label, plural_label) VALUES ('package', TRUE, 'Package', 'Packages');
INSERT INTO object (name, setup, label, plural_label) VALUES ('page_layouts', TRUE, 'Page Layouts', 'Page Layoutses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('path_builder', TRUE, 'Path Builder', 'Path Builders');
INSERT INTO object (name, setup, label, plural_label) VALUES ('permission_sets', TRUE, 'Permission Sets', 'Permission Setses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('process_builders', TRUE, 'Process Builders', 'Process Builderses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('products', TRUE, 'Products', 'Productses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('profile', TRUE, 'Profile', 'Profiles');
INSERT INTO object (name, setup, label, plural_label) VALUES ('regions', TRUE, 'Regions', 'Regionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('remote_site_setting', TRUE, 'Remote Site Setting', 'Remote Site Settings');
INSERT INTO object (name, setup, label, plural_label) VALUES ('reports', TRUE, 'Reports', 'Reportses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('roles', TRUE, 'Roles', 'Roleses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('sales', TRUE, 'Sales', 'Saleses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('salesforce_metadata', TRUE, 'Salesforce Metadata', 'Salesforce Metadatas');
INSERT INTO object (name, setup, label, plural_label) VALUES ('salesforce_settings', TRUE, 'Salesforce Settings', 'Salesforce Settingses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('salesforce_sync', TRUE, 'Salesforce Sync', 'Salesforce Syncs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('search_layouts', TRUE, 'Search Layouts', 'Search Layoutses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('session_log', TRUE, 'Session Log', 'Session Logs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('setup', TRUE, 'Setup', 'Setups');
INSERT INTO object (name, setup, label, plural_label) VALUES ('sf_integration_lead', TRUE, 'Sf Integration Lead', 'Sf Integration Leads');
INSERT INTO object (name, setup, label, plural_label) VALUES ('sharing_records', TRUE, 'Sharing Records', 'Sharing Recordses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('sharing_rules', TRUE, 'Sharing Rules', 'Sharing Ruleses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('tab_permissions', TRUE, 'Tab Permissions', 'Tab Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('tables_metadata', TRUE, 'Tables Metadata', 'Tables Metadatas');
INSERT INTO object (name, setup, label, plural_label) VALUES ('tabs', TRUE, 'Tabs', 'Tabses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('task', TRUE, 'Task', 'Tasks');
INSERT INTO object (name, setup, label, plural_label) VALUES ('telephony_config', TRUE, 'Telephony Config', 'Telephony Configs');
INSERT INTO object (name, setup, label, plural_label) VALUES ('theme', TRUE, 'Theme', 'Themes');
INSERT INTO object (name, setup, label, plural_label) VALUES ('user_group', TRUE, 'User Group', 'User Groups');
INSERT INTO object (name, setup, label, plural_label) VALUES ('user_group_users', TRUE, 'User Group Users', 'User Group Userses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('user_login_history', TRUE, 'User Login History', 'User Login Histories');
INSERT INTO object (name, setup, label, plural_label) VALUES ('users', TRUE, 'Users', 'Userses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('users_user_permissions', TRUE, 'Users User Permissions', 'Users User Permissionses');
INSERT INTO object (name, setup, label, plural_label) VALUES ('webhook', TRUE, 'Webhook', 'Webhooks');
INSERT INTO object (name, setup, label, plural_label) VALUES ('workflow', TRUE, 'Workflow', 'Workflows');
INSERT INTO object (name, setup, label, plural_label) VALUES ('workflow_edge', TRUE, 'Workflow Edge', 'Workflow Edges');
INSERT INTO object (name, setup, label, plural_label) VALUES ('workflow_node', TRUE, 'Workflow Node', 'Workflow Nodes');
INSERT INTO object (name, setup, label, plural_label) VALUES ('workflow_rules', TRUE, 'Workflow Rules', 'Workflow Ruleses');
